spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=NaniNatural@116

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true